### ISSUE TITLE
lede源码编译shadowsocks mbedtls 补丁问题

### ISSUE THREAD

**Issue by juyyao** [wongsyrone/lede-1#20]
使用你的补丁出现如下错误
Applying ./patches/999-tweak-config-for-shadowsocks.patch using plaintext: 
patching file include/mbedtls/config.h
patch: ***\* malformed patch at line 56: \* \def MBEDTLS_TIMING_C

Patch failed!  Please fix ./patches/999-tweak-config-for-shadowsocks.patch!
Makefile:69: recipe for target '/home/juyyao/lede/lede/build_dir/target-mipsel_24kc_musl-1.1.15/mbedtls-2.3.0/.prepared_4908a6bbe3c499220ff465087ea9844e' failed
感谢

**Comment by wongsyrone** [comment]
我编译是没问题的，自己检查格式。

**Comment by juyyao** [comment]
源码有问题好像,补丁最后56行代码不完整,删了之后编译通过

**Comment by wongsyrone** [comment]
确保修改项后面有三行，包括空行

On Oct 12, 2016 11:20 AM, "juyyao" notifications@github.com wrote:

源码有问题好像,补丁最后56行代码不完整,删了之后编译通过

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
https://github.com/wongsyrone/lede-1/issues/20#issuecomment-253108639,
or mute
the thread
